python logix.py
[logix] Loaded config from /home/pachagx/SageMaker/pachagx/logix-tier3-aws 2/logix-tool_clean_for_sharing/config.json.
[logix] Reading LogiX credentials from AWS Secrets Manager secret '/nonprod/abt-aa-neustadt-creon-202001007/logix_creds'...
[logix] Loaded LogiX credentials from AWS Secrets Manager.
[logix] Launching Chromium (headless), profile=/home/pachagx/.logix_playwright_profile
[logix] Navigating to https://packos.logix.abbott.com/world
[logix] Existing session detected - already authenticated.
[logix] UI language already set to EN.
[logix] === Export I: Site OEE Report (CSV) ===
[logix] Selecting site 'Neustadt' from the world overview...
[logix] Entered site 'Neustadt' (https://packos.logix.abbott.com/02b8ee12-f788-4d80-9aba-6572c1bb9aaa/dashboard/lines).
[logix] Opening 'Reports' (left nav)...
[logix] Opening the 'REPORTS DOWNLOAD' tab...
[logix] Opening 'Site OEE Report'...
[logix] Selecting all MUs/Lines (excluding offline lines / Linie 66)...
[logix] Setting Period = 'Custom'...
[logix] Setting OEE date range = 01.01.2026 .. 12.09.2026 ...
[logix] OEE date range confirmed = 01.01.2026 - 12.09.2026
[logix] Clicking 'Export report' and waiting for CSV download...
[logix] Saved download -> /home/pachagx/logix_exports/20260912_235944_site-oee-report_2026-01-01-2026-09-12.csv
[logix] OEE export took 34s.
[logix] OEE export: 17043 rows, 255 distinct days, earliest 2026-01-01
[logix] === Export II: Production - Bereich MU-Packaging (XLSX) ===
[logix] Opening the 'PRODUCTION' tab...
[logix] Selecting scope 'Neustadt' > 'Bereich MU-Packaging'...
[logix] Setting Period = 'Year'...
[logix]   ! no scoped 'Year' option found; falling back to page-wide text match.
[logix] Production period confirmed via URL = Year / This year.
[logix] State capture 'production_period' -> /home/pachagx/logix_exports/20260912_235952_production_period.png
[logix]   url: https://packos.logix.abbott.com/02b8ee12-f788-4d80-9aba-6572c1bb9aaa/reports/production?period=5&moment=thisYear&elementId=3ab29e64-af44-4e86-806b-621c70c5815e&selectedTaxonomy=&selectedWorkEventsTaxonomy=
[logix] Opening the report (table) view...
[logix] ERROR (attempt 1): Could not open the Production report table modal.
[logix] Saved error screenshot -> /home/pachagx/logix_exports/error_screenshot_attempt1.png
[logix] Saved error page HTML -> /home/pachagx/logix_exports/error_screenshot_attempt1.html
[logix] Closing browser (saving session; can take a few seconds)...
[logix] Retrying (attempt 2/3) after 30s...
[logix] Loaded config from /home/pachagx/SageMaker/pachagx/logix-tier3-aws 2/logix-tool_clean_for_sharing/config.json.
[logix] Reading LogiX credentials from AWS Secrets Manager secret '/nonprod/abt-aa-neustadt-creon-202001007/logix_creds'...
[logix] Loaded LogiX credentials from AWS Secrets Manager.
[logix] Launching Chromium (headless), profile=/home/pachagx/.logix_playwright_profile
[logix] Navigating to https://packos.logix.abbott.com/world
[logix] Existing session detected - already authenticated.
[logix] UI language already set to EN.
[logix] === Export I: Site OEE Report (CSV) ===
[logix] Selecting site 'Neustadt' from the world overview...
[logix] Entered site 'Neustadt' (https://packos.logix.abbott.com/02b8ee12-f788-4d80-9aba-6572c1bb9aaa/dashboard/lines).
[logix] Opening 'Reports' (left nav)...
[logix] Opening the 'REPORTS DOWNLOAD' tab...
[logix] Opening 'Site OEE Report'...
[logix] Selecting all MUs/Lines (excluding offline lines / Linie 66)...
[logix] Setting Period = 'Custom'...
[logix] Setting OEE date range = 01.01.2026 .. 13.09.2026 ...
[logix] OEE date range confirmed = 01.01.2026 - 13.09.2026
[logix] Clicking 'Export report' and waiting for CSV download...
[logix] Saved download -> /home/pachagx/logix_exports/20260913_000134_site-oee-report_2026-01-01-2026-09-13.csv
[logix] OEE export took 12s.
[logix] OEE export: 17087 rows, 256 distinct days, earliest 2026-01-01
[logix] === Export II: Production - Bereich MU-Packaging (XLSX) ===
[logix] Opening the 'PRODUCTION' tab...
[logix] Selecting scope 'Neustadt' > 'Bereich MU-Packaging'...
[logix] Setting Period = 'Year'...
[logix]   ! no scoped 'Year' option found; falling back to page-wide text match.
[logix] Production period confirmed via URL = Year / This year.
[logix] State capture 'production_period' -> /home/pachagx/logix_exports/20260913_000142_production_period.png
[logix]   url: https://packos.logix.abbott.com/02b8ee12-f788-4d80-9aba-6572c1bb9aaa/reports/production?period=5&moment=thisYear&elementId=3ab29e64-af44-4e86-806b-621c70c5815e&selectedTaxonomy=&selectedWorkEventsTaxonomy=
[logix] Opening the report (table) view...
[logix] Clicking 'Excel' and waiting for XLSX download...
[logix] Saved download -> /home/pachagx/logix_exports/20260913_000144_Production.xlsx
[logix] Production export took 0s.
[logix]   ! openpyxl not installed; skipping Production coverage check.
[logix] Done. Files created:
[logix]   - /home/pachagx/logix_exports/20260913_000134_site-oee-report_2026-01-01-2026-09-13.csv
[logix]   - /home/pachagx/logix_exports/20260913_000144_Production.xlsx
[logix] Closing browser (saving session; can take a few seconds)...
(logix) (base) pachagx@APLTiHSOfxk5ELd:~/SageMaker/pachagx/logix-tier3-aws 2/logix-tool_clean_for_sharing$ python logix.py
[logix] Loaded config from /home/pachagx/SageMaker/pachagx/logix-tier3-aws 2/logix-tool_clean_for_sharing/config.json.
[logix] Reading LogiX credentials from AWS Secrets Manager secret '/nonprod/abt-aa-neustadt-creon-202001007/logix_creds'...
[logix] Loaded LogiX credentials from AWS Secrets Manager.
[logix] Launching Chromium (headless), profile=/home/pachagx/.logix_playwright_profile
[logix] Navigating to https://packos.logix.abbott.com/world
[logix] Existing session detected - already authenticated.
[logix] UI language already set to EN.
[logix] === Export I: Site OEE Report (CSV) ===
[logix] Selecting site 'Neustadt' from the world overview...
[logix] Entered site 'Neustadt' (https://packos.logix.abbott.com/02b8ee12-f788-4d80-9aba-6572c1bb9aaa/dashboard/lines).
[logix] Opening 'Reports' (left nav)...
[logix] Opening the 'REPORTS DOWNLOAD' tab...
[logix] Opening 'Site OEE Report'...
[logix] Selecting all MUs/Lines (excluding offline lines / Linie 66)...
[logix] Setting Period = 'Custom'...
[logix] Setting OEE date range = 01.01.2026 .. 13.09.2026 ...
[logix] OEE date range confirmed = 01.01.2026 - 13.09.2026
[logix] Clicking 'Export report' and waiting for CSV download...
[logix] Saved download -> /home/pachagx/logix_exports/20260913_000531_site-oee-report_2026-01-01-2026-09-13.csv
[logix] OEE export took 14s.
[logix] OEE export: 17087 rows, 256 distinct days, earliest 2026-01-01
[logix] === Export II: Production - Bereich MU-Packaging (XLSX) ===
[logix] Opening the 'PRODUCTION' tab...
[logix] Selecting scope 'Neustadt' > 'Bereich MU-Packaging'...
[logix] Setting Period = 'Year'...
[logix]   ! no scoped 'Year' option found; falling back to page-wide text match.
[logix] Production period confirmed via URL = Year / This year.
[logix] State capture 'production_period' -> /home/pachagx/logix_exports/20260913_000539_production_period.png
[logix]   url: https://packos.logix.abbott.com/02b8ee12-f788-4d80-9aba-6572c1bb9aaa/reports/production?period=5&moment=thisYear&elementId=3ab29e64-af44-4e86-806b-621c70c5815e&selectedTaxonomy=&selectedWorkEventsTaxonomy=
[logix] Opening the report (table) view...
[logix] Clicking 'Excel' and waiting for XLSX download...
[logix] Saved download -> /home/pachagx/logix_exports/20260913_000551_Production.xlsx
[logix] Production export took 1s.
[logix]   ! openpyxl not installed; skipping Production coverage check.
[logix] Done. Files created:
[logix]   - /home/pachagx/logix_exports/20260913_000531_site-oee-report_2026-01-01-2026-09-13.csv
[logix]   - /home/pachagx/logix_exports/20260913_000551_Production.xlsx
[logix] Closing browser (saving session; can take a few seconds)...
(logix) (base) pachagx@APLTiHSOfxk5ELd:~/SageMaker/pachagx/logix-tier3-aws 2/logix-tool_clean_for_sharing$ 
